import React, { useState, useEffect } from 'react';
import { Mail, X, Copy, FileText, ChevronRight } from 'lucide-react';

interface EmailDialogProps {
    isOpen: boolean;
    onClose: () => void;
    defaultSubject: string;
    defaultBody: string;
    isDarkMode: boolean;
}

const EmailDialog: React.FC<EmailDialogProps> = ({
    isOpen,
    onClose,
    defaultSubject,
    defaultBody,
    isDarkMode
}) => {
    const [subject, setSubject] = useState(defaultSubject);
    const [body, setBody] = useState(defaultBody);
    const [copied, setCopied] = useState(false);
    const [emailSignature, setEmailSignature] = useState(`
--
Generated by SpikedAI
Visit us at: https://www.spiked.ai
    `.trim());
    const [showSignatureEditor, setShowSignatureEditor] = useState(false);
    const [previewUrl, setPreviewUrl] = useState('');
    const [recipients, setRecipients] = useState('');
    const [ccRecipients, setCcRecipients] = useState('');
    const [bccRecipients, setBccRecipients] = useState('');

    useEffect(() => {
        // Create the preview URL when the body changes
        const transcriptText = encodeURIComponent(body);
        const summaryUrl = `${window.location.origin}/meeting-summary?transcript=${transcriptText}`;
        setPreviewUrl(summaryUrl);
    }, [body]);

    const handleOpenWebSummary = () => {
        window.open(previewUrl, '_blank');
    };

    if (!isOpen) return null;
    
    const copyToClipboard = async () => {
        try {
            await navigator.clipboard.writeText(`${subject}\n\n${body}`);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error('Failed to copy:', err);
        }
    };

    const getEmailBody = (signature: string) => {
        return `${body}\n\n${signature}`;
    };

    const handleGmailClick = (signature: string) => {
        let gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&tf=1&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(getEmailBody(signature))}`;
        if (recipients) {
            gmailUrl += `&to=${encodeURIComponent(recipients)}`;
        }
        if (ccRecipients) {
            gmailUrl += `&cc=${encodeURIComponent(ccRecipients)}`;
        }
        if (bccRecipients) {
            gmailUrl += `&bcc=${encodeURIComponent(bccRecipients)}`;
        }
        window.open(gmailUrl, '_blank');
    };

    const handleYahooClick = (signature: string) => {
        let yahooUrl = `https://compose.mail.yahoo.com/?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(getEmailBody(signature))}`;
        if (recipients) {
            yahooUrl += `&to=${encodeURIComponent(recipients)}`;
        }
        if (ccRecipients) {
            yahooUrl += `&cc=${encodeURIComponent(ccRecipients)}`;
        }
        if (bccRecipients) {
            yahooUrl += `&bcc=${encodeURIComponent(bccRecipients)}`;
        }
        window.open(yahooUrl, '_blank');
    };

    const handleOutlookClick = (signature: string) => {
        let outlookUrl = `https://outlook.live.com/mail/0/deeplink/compose?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(getEmailBody(signature))}`;
        if (recipients) {
            outlookUrl += `&to=${encodeURIComponent(recipients)}`;
        }
        if (ccRecipients) {
            outlookUrl += `&cc=${encodeURIComponent(ccRecipients)}`;
        }
        if (bccRecipients) {
            outlookUrl += `&bcc=${encodeURIComponent(bccRecipients)}`;
        }
        window.open(outlookUrl, '_blank');
    };

    return (
        <div className="fixed inset-0 flex items-center justify-center z-50">
            {/* Backdrop with blur */}
            <div 
                className="absolute inset-0 backdrop-blur-sm bg-black/40" 
                onClick={onClose}
            ></div>

            {/* Dialog */}
            <div className={`relative w-[95%] max-w-2xl rounded-xl shadow-2xl transform transition-all duration-300 scale-100 ${
                isDarkMode 
                    ? 'bg-gray-900 border border-gray-700' 
                    : 'bg-white border border-gray-200'
            }`}>
                {/* Header */}
                <div className={`flex items-center justify-between p-6 border-b ${
                    isDarkMode ? 'border-gray-700' : 'border-gray-200'
                }`}>
                    <div className="flex items-center space-x-3">
                        <div className={`p-2 rounded-lg ${
                            isDarkMode ? 'bg-blue-500/10' : 'bg-blue-50'
                        }`}>
                            <Mail className={`w-5 h-5 ${
                                isDarkMode ? 'text-blue-400' : 'text-blue-500'
                            }`} />
                        </div>
                        <h2 className={`text-xl font-semibold ${
                            isDarkMode ? 'text-white' : 'text-gray-900'
                        }`}>
                            Share Meeting Summary
                        </h2>
                    </div>
                    <button
                        onClick={onClose}
                        className={`p-2 rounded-lg transition-colors ${
                            isDarkMode 
                                ? 'hover:bg-gray-800 text-gray-400 hover:text-gray-300' 
                                : 'hover:bg-gray-100 text-gray-500 hover:text-gray-700'
                        }`}
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                {/* Content */}
                <div className="p-6 space-y-6">
                    

                    {/* Subject */}
                    <div className="space-y-2">
                        <label 
                            htmlFor="subject" 
                            className={`block text-sm font-medium ${
                                isDarkMode ? 'text-gray-300' : 'text-gray-700'
                            }`}
                        >
                            Subject
                        </label>
                        <input
                            id="subject"
                            type="text"
                            value={subject}
                            onChange={(e) => setSubject(e.target.value)}
                            className={`w-full px-4 py-3 rounded-lg border focus:outline-none focus:ring-2 transition-shadow ${
                                isDarkMode 
                                    ? 'bg-gray-800 border-gray-700 text-white focus:ring-blue-500/50' 
                                    : 'bg-white border-gray-300 text-gray-900 focus:ring-blue-500/50'
                            }`}
                            placeholder="Email subject"
                        />
                    </div>

                    {/* Message */}
                    <div className="space-y-2">
                        <label 
                            htmlFor="body" 
                            className={`block text-sm font-medium ${
                                isDarkMode ? 'text-gray-300' : 'text-gray-700'
                            }`}
                        >
                            Message
                        </label>
                        <div className="relative">
                            <textarea
                                id="body"
                                value={body}
                                onChange={(e) => setBody(e.target.value)}
                                rows={8}
                                className={`w-full px-4 py-3 rounded-lg border focus:outline-none focus:ring-2 transition-shadow ${
                                    isDarkMode 
                                        ? 'bg-gray-800 border-gray-700 text-white focus:ring-blue-500/50' 
                                        : 'bg-white border-gray-300 text-gray-900 focus:ring-blue-500/50'
                                }`}
                                placeholder="Email content"
                            />
                            <button
                                onClick={copyToClipboard}
                                className={`absolute top-2 right-2 p-2 rounded-md transition-colors ${
                                    isDarkMode
                                        ? 'hover:bg-gray-700 text-gray-400 hover:text-gray-300'
                                        : 'hover:bg-gray-100 text-gray-500 hover:text-gray-700'
                                }`}
                                title="Copy to clipboard"
                            >
                                <Copy className="w-4 h-4" />
                            </button>
                            {copied && (
                                <div className={`absolute -top-2 right-2 px-2 py-1 rounded text-xs ${
                                    isDarkMode ? 'bg-gray-700 text-gray-300' : 'bg-gray-800 text-white'
                                }`}>
                                    Copied!
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Footer with email service buttons */}
                {/* Footer with actions */}
                <div className={`p-6 space-y-4 border-t ${
                    isDarkMode ? 'border-gray-700' : 'border-gray-200'
                }`}>
                    {/* Preview button */}
                    <div className="flex justify-center">
                        <button
                            onClick={handleOpenWebSummary}
                            className="flex items-center justify-center px-6 py-2 rounded-lg text-white bg-green-500 hover:bg-green-600 transition-colors shadow-lg shadow-green-500/20"
                        >
                            <FileText className="w-5 h-5 mr-2" />
                            Open Web Summary
                        </button>
                    </div>

                    {/* Signature Editor */}
                    <div className="space-y-2">
                        <button
                            onClick={() => setShowSignatureEditor(!showSignatureEditor)}
                            className={`flex items-center text-sm font-medium ${
                                isDarkMode ? 'text-gray-300 hover:text-white' : 'text-gray-600 hover:text-gray-900'
                            }`}
                        >
                            <ChevronRight className={`w-4 h-4 mr-1 transform transition-transform ${
                                showSignatureEditor ? 'rotate-90' : ''
                            }`} />
                            Email Signature
                        </button>
                        
                        {showSignatureEditor && (
                            <div className="space-y-2">
                                <textarea
                                    value={emailSignature}
                                    onChange={(e) => setEmailSignature(e.target.value)}
                                    rows={4}
                                    className={`w-full px-3 py-2 text-sm rounded-lg border focus:outline-none focus:ring-2 transition-shadow ${
                                        isDarkMode 
                                            ? 'bg-gray-800 border-gray-700 text-white focus:ring-blue-500/50' 
                                            : 'bg-white border-gray-300 text-gray-900 focus:ring-blue-500/50'
                                    }`}
                                    placeholder="Enter your email signature..."
                                />
                            </div>
                        )}
                    </div>

                    {/* Validation message */}
                    {!recipients && (
                        <div className={`p-3 rounded-lg border-l-4 border-yellow-500 bg-yellow-50 dark:bg-yellow-900/20`}>
                            <p className={`text-sm ${isDarkMode ? 'text-yellow-200' : 'text-yellow-800'}`}>
                                💡 <strong>Tip:</strong> Add recipient emails above, then click any email service to open with pre-filled content.
                            </p>
                        </div>
                    )}

                    {/* Email client buttons */}
                    <div className="flex flex-col sm:flex-row gap-3">
                        <button
                            onClick={() => handleGmailClick(emailSignature)}
                            className="flex-1 flex items-center justify-center px-4 py-3 rounded-lg text-white bg-red-500 hover:bg-red-600 transition-colors shadow-lg shadow-red-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={!recipients.trim()}
                        >
                            <Mail className="w-5 h-5 mr-2" />
                            Open in Gmail
                        </button>
                        <button
                            onClick={() => handleYahooClick(emailSignature)}
                            className="flex-1 flex items-center justify-center px-4 py-3 rounded-lg text-white bg-purple-500 hover:bg-purple-600 transition-colors shadow-lg shadow-purple-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={!recipients.trim()}
                        >
                            <Mail className="w-5 h-5 mr-2" />
                            Open in Yahoo
                        </button>
                        <button
                            onClick={() => handleOutlookClick(emailSignature)}
                            className="flex-1 flex items-center justify-center px-4 py-3 rounded-lg text-white bg-blue-500 hover:bg-blue-600 transition-colors shadow-lg shadow-blue-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                            disabled={!recipients.trim()}
                        >
                            <Mail className="w-5 h-5 mr-2" />
                            Open in Outlook
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default EmailDialog;